[tool.poetry]
name = "lanor"
version = "0.1.0"
description = "LANOR an AI agent for Hybrid Cloud Security"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
